name: Docker Images to DockerHub
on:
  pull_request:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate tag
      uses: frabert/replace-string-action@v2.0
      id: genTag
      with:
        pattern: '.*(\d+\.\d+\.\d+).*'
        string: "${{ github.event.release.tag_name }}"
        replace-with: '$1'

    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push main image
      id: docker_build_main
      uses: docker/build-push-action@v2
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        file: ./Dockerfile
        context: .
        push: true
        tags: |
          transferwiseworkspace/cloudflare-prometheus-exporter:${{ steps.genTag.outputs.replaced }}
          transferwiseworkspace/cloudflare-prometheus-exporter:latest

    - name: Image digests
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        echo ${{ steps.docker_build_main.outputs.digest }}
        echo ${{ steps.docker_build_barebone.outputs.digest }}
        echo ${{ steps.docker_build_default.outputs.digest }}1
